language: node_js
node_js: lts/*

addons:
  ssh_known_hosts: umiringo.com

cache: yarn

install: 
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script: 
  - hugo version
  - hugo

before_deploy:
  - openssl aes-256-cbc -K $encrypted_7051ac01cf89_key -iv $encrypted_7051ac01cf89_iv
    -in .travis/travis.enc -out ~/.ssh/id_rsa -d
  - eval $(ssh-agent -s)
  - chmod 600 ~/.ssh/id_rsa
  - cho -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config