language: node_js
node_js: lts/*

addons:
  ssh_known_hosts: umiringo.com

cache: yarn

install: 
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script: 
  - hugo version
  - hugo

before_deploy:
  - openssl aes-256-cbc -K $encrypted_3c7444b0f500_key -iv $encrypted_3c7444b0f500_iv -in travis.enc -out /tmp/travis_rsa -d  
  - eval $(ssh-agent -s)
  - chmod 600 /tmp/travis_rsa
  - ssh-add /tmp/travis_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  - provider: script
    script: rsync -r -e 'ssh -p ${DEPLOY_PORT}' --delete-after -v -az public/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
    skip_cleanup: true
    on:
      branch: master

branches:
  only:
    - master