baseURL = "http://www.umiringo.com/"
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
title = "umiringo's nest"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "light-hugo"
enableGitInfo = false # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。
disablePathToLower = true # 禁止将路径全部改为小写
# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
#pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"
markup = "markdown" # 格式化 markdown
hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 10                                           # 首页每页显示的文章数
disqusShortname = ""      # disqus_shortname
# googleAnalytics = "UA-138883536-1"      # UA-XXXXXXXX-X
copyright = "© Copyright 2019 umiringo"            # default: author.name ↓        # 默认为下面配置的author.name ↓

[blackfriday]
  smartypants = false

[author]                  # essential                     # 必需
  name = "umiringo"

[params]
  description = "fuck gfw"
  email = "umiringo42@gmail.com"
  github = "umiringo"
  twitter = "umiringo42"
  facebook = "umiringo42"
  logo = "/images/logo.png"
  
